# this experiment computes the correlation between annotations and pairs of
# measurements for a DTW metric with parameters defined below.

# dimensions available:
# ['ax', 'ay', 'az',        : RIOT acceleration
#  'gx', 'gy', 'gz',        : RIOT gyroscope
#  'ox', 'oy', 'oz',        : orientation
#  'q1', 'q2', 'q3', 'q4',  : orientation
#  'roll', 'pitch', 'yaw',  : orientation
#  'px', 'py', 'pz',        : MOCAP position
#  'px0', 'py0', 'pz0',     : position filtered
#  'px1', 'py1', 'pz1',     : velocity filtered
#  'px2', 'py2', 'pz2']     : acceleration filtered
# dims: ['px0', 'py0', 'pz0', 'px1', 'py1', 'pz1', 'px2', 'py2', 'pz2']
# dims: ['px0', 'py0', 'pz0', 'ax', 'ay', 'az', 'gx', 'gy', 'gz']
# dtw.distance: [default, diag, full]

data:
  normalise: True
  dims: ['px0', 'py0', 'pz0', 'ax0', 'ay0', 'az0', 'gx0', 'gy0', 'gz0', 'px1', 'py1', 'pz1', 'px2', 'py2', 'pz2']

dtw:
  radius: 10
  distance: 'diag'

opt:
  n_iter: 10
  method: 'L-BFGS-B'
  init_scale: 1
  eps: 0.001
  n_cores: 10
  regularisation: 1

mlflow:
  experiment_id: 5

cv:
  active: True
  n_splits: 2
  n_repeats: 8
  random_state: 42
  test_size: 0.5

annotations: 'all'
