[tool.kedro]
package_name = "metric_learning"
project_name = "Metric Learning"
project_version = "0.17.2"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
known_third_party = "kedro"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/metric_learning -ra"""
