# this experiment computes the correlation between annotations and pairs of
# measurements for a DTW metric with parameters defined below.

# dimensions available:
# ['ax', 'ay', 'az',        : RIOT acceleration
#  'gx', 'gy', 'gz',        : RIOT gyroscope
#  'ox', 'oy', 'oz',        : orientation
#  'q1', 'q2', 'q3', 'q4',  : orientation
#  'roll', 'pitch', 'yaw',  : orientation
#  'px', 'py', 'pz',        : MOCAP position
#  'px0', 'py0', 'pz0',     : position filtered
#  'px1', 'py1', 'pz1',     : velocity filtered
#  'px2', 'py2', 'pz2']     : acceleration filtered

data:
  normalise: True
  dims: ['px0', 'py0', 'pz0', 'px1', 'py1', 'pz1', 'px2', 'py2', 'pz2', 'ax0', 'ay0', 'az0', 'gx0', 'gy0', 'gz0']

dtw:
  radius: 10
  average: True
  fun: sum

opt:
  n_regions: [2, 5, 7, 12, 15, 20, 25, 30, 40, 50, 80]
  n_iter: 10
  method: 'L-BFGS-B'
  init_scale: 1


cv:
  active: True
  n_splits: 2
  n_repeats: 4
  random_state: 46
  test_size: 0.5


mlflow:
  experiment_id: 24

cross_validation: True

annotations: all
